pass mask when creating policy_l2 flowmod and drop "type" argument
bisdn/rofl-ofdpa pull request #109
Opened 2021-01-07 15:26 UTC by jklare

* the enable_policy_l2 and disable_policy_l2 functions seem to be unused
  so we can refactor and reuse them for the purpose of copying e.g IS-IS
  PDUs to the controller
* added the argument "mask" to allow passing a range of MACs
* dropped unused argument "type"

Signed-off-by: Jan Klare <jan.klare@bisdn.de>

2021-01-07 15:45 UTC, KanjiMonster requested changes
Apart from a few code style nitpicks LGTM

2021-01-07 15:45 UTC, KanjiMonster commented on lib/rofl_ofdpa_fm_driver.cpp
> +                                                  ) {
```suggestion
                                                  const rofl::caddress_ll &mask) {
```

2021-01-07 15:45 UTC, KanjiMonster commented on lib/rofl_ofdpa_fm_driver.cpp
> +  fm.set_match().set_eth_dst(mac,mask);
```suggestion
  fm.set_match().set_eth_dst(mac, mask);
```

2021-01-07 15:45 UTC, KanjiMonster commented on lib/rofl_ofdpa_fm_driver.cpp
> +                                                   ) {
```suggestion
                                                   const rofl::caddress_ll &mask) {
```

2021-01-07 15:45 UTC, KanjiMonster commented on lib/rofl_ofdpa_fm_driver.cpp
> +  fm.set_match().set_eth_dst(mac,mask);
```suggestion
  fm.set_match().set_eth_dst(mac, mask);
```

2021-01-08 14:53 UTC, rubensfig commented
LGTM

2021-01-08 14:53 UTC, rubensfig approved these changes

2021-01-08 14:53 UTC, merged